### ISSUE TITLE
Adding redis and elasticsearch

### ISSUE THREAD

**Issue by bagussatria** [michelson/dante-stories#12]
Im new on nodejs, when i try to push this on heroku it cant run. I thought i hadn't add redis and elasticsearch base what author said.

Can you provide me a tutorial how to add redis and elasticsearch. also did  i need to link creditcard on heroku to try elasticsearh add on

**Comment by michelson** [comment]
Hi @bagussatria , this is an ruby on rails application, not a node application. You can add addons for redis and elasticsearch without a card. 
check the readme , it's all you need to get going, and you should check how ruby on rails applications works

best!
