### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by nodiscc** [michelson/dante-stories#20]
Hi,
as part of https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1767 we noticed that your project's website https://dante-stories.herokuapp.com/ is down (`No such app`). Are you maintaining the website/is it supposed to be up?

Please let us know if the website link should be removed from https://github.com/awesome-selfhosted/awesome-selfhosted

**Comment by michelson** [comment]
site is working now, thanks for reporting
