### ISSUE TITLE
Admin Panel?

### ISSUE THREAD

**Issue by mzch** [michelson/dante-stories#23]
I tried to login admin panel via `/admins/sign_in` but dante-stories reported an error.

<img width="1273" alt="スクリーンショット 2019-11-14 8 43 24" src="https://user-images.githubusercontent.com/621178/68813971-dd9da000-06ba-11ea-9743-d27229c19e8e.png">

Any idea?

**Comment by michelson** [comment]
update role on user to `user.update(role: "admin")`

then visit `/admin/dashboard`

Atte.
Miguel Michelson Martinez
www.vadb.org <http://vadb.org>

**Comment by mzch** [comment]
Thanks for you advice, @michelson , but stories said, "access denied".

**Comment by mzch** [comment]
Sorry, I missed update suggestion. It went well, Thanks!
