### ISSUE TITLE
Demo app - logging in with google fails

### ISSUE THREAD

**Issue by seanfcarroll** [michelson/dante-stories#8]
<img width="1044" alt="screen shot 2018-11-19 at 15 05 51" src="https://user-images.githubusercontent.com/11340230/48711878-9fd37c00-ec0c-11e8-951f-2703a9479004.png">

**Comment by michelson** [comment]
Hi @seanfcarroll. This happens to your own implementation ? or just happen in the demo site ? if so, then yes. It will not work because I haven't configured the third party authorization. The google error tells that the configuration is missing

**Comment by seanfcarroll** [comment]
Thanks.
