### ISSUE TITLE
Federation/ActivityPub support

### ISSUE THREAD

**Issue by mkljczk** [michelson/dante-stories#9]
I think it would be awesome to see [ActivityPub](https://www.w3.org/TR/activitypub/) support in this project, so instances of dante-stories could create a big network, comparable to Medium, but decentralized. There are already two really good blogging platforms with ActivityPub support — [WriteFreely](https://writefreely.org/) and [Plume](https://joinplu.me) and two WordPress plugins adding ActivityPub support — [Pterotype](https://getpterotype.com) and [wordpress-activitypub](https://github.com/pfefferle/wordpress-activitypub). There are two projects written in Ruby I know that support ActivityPub — [Mastodon](https://joinmastodon.org) and [Prismo](https://gitlab.com/mbajur/prismo).
It would be nice to see at least basic federation support — posts propagation, ability to follow dante-stories authors from Mastodon/Pleroma/Misskey etc.

**Comment by michelson** [comment]
This looks very interesting. I know nothing about this protocol yet so I must dive into it. 
We could keep this issue to document and put references of ActivityPub

**Comment by michelson** [comment]
in spanish: https://vimeo.com/256483933

**Comment by m4sk1n** [comment]
Basic ActivityPub development tutorials (Ruby) from Mastodon author:
https://blog.joinmastodon.org/2018/06/how-to-implement-a-basic-activitypub-server/
https://blog.joinmastodon.org/2018/07/how-to-make-friends-and-verify-requests/

**Comment by m4sk1n** [comment]
I totally forgot that Prismo author is working on ActivityPub gem, that should be helpful: https://gitlab.com/prismosuite/activitypub-rails
